apiVersion: v1
kind: Service
metadata:
  name: kubernetes-example
  labels:
    app: kubernetes-example
spec:
  type: ClusterIP
  selector:
    app: kubernetes-example
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP